### ISSUE TITLE
Add link to the Nevermore GitHub

### ISSUE THREAD

**Issue by devSparkle** [NevermoreFramework/nevermoreframework.github.io#2]
The Nevermore website should feature prominent links to the:

- [x] Nevermore organization
- [x] Nevermore repository
- [ ] Nevermore installation plugin

It should be considered whether the links direct the user to the repository or to the page containing the latest release. We should further consider most users are not familiar with GitHub.

**Comment by Narrev** [comment]
The installation plug-in should handle installing. Perhaps the website should merely sell the user on the plug-in and let the plug-in do the rest?

**Comment by devSparkle** [comment]
This issue is marked as completed until such time as the *Nevermore installation plugin* is released to the public.
