### ISSUE TITLE
Fix Command Bar code

### ISSUE THREAD

**Issue by devSparkle** [NevermoreFramework/nevermoreframework.github.io#5]
The *Run in the Command Bar* code section should, when copy-pasted, substitute `NevermoreRepo` with `https://raw.githubusercontent.com/Quenty/NevermoreEngine/master/Install.lua`.

**Comment by Narrev** [comment]
The end-goal is to not use the command bar, but to use the plug-in instead for installing

**Comment by devSparkle** [comment]
Agreed @Narrev, however, the plugin has not been publicly released and there is nothing wrong with supporting a secondary method.

**Comment by Narrev** [comment]
This has been temporarily resolved
